### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by r007** [tracker1/gulp-header#33]
I have an issue.

This is my gulp tast:
```js
var gulp          = require('gulp')
  , gutil         = require('gulp-util')
  , header        = require('gulp-header')
  , pkg           = require('../../package.json')

var banner = {
  theme :
  '/**n' +
  ' * Banner content: <%= package.name %>/n' +
  ' */'
};

gulp.task('styles-libsass', function() {
  return gulp.src(config.build.src)
  // ...
  // Here goes compilation and minification of my scss stylesheets
  // ...
  .pipe(header(banner.theme, { package : pkg }))
  .pipe(gulp.dest(config.build.dest)); // Drops the unminified CSS file into the `build` folder
});
```
Error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'url' of undefined
    at eval (eval at <anonymous> (/myproject/source/node_modules/lodash.template/index.js:349:12), <anonymous>:12:29)
    at wrapped (/myproject/source/node_modules/gulp-util/lib/template.js:19:12)
    at Object.module.exports [as template] (/myproject/source/node_modules/gulp-util/lib/template.js:22:18)
    at DestroyableTransform.TransformStream [as _transform] (/myproject/source/node_modules/gulp-header/index.js:34:26)
    at DestroyableTransform.Transform._read (/myproject/source/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/myproject/source/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/myproject/source/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/myproject/source/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/myproject/source/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Transform.ondata (_stream_readable.js:555:20)
```

Line where error occurs:

```js
var template = data === false ? headerText : gutil.template(headerText, extend({file : file, filename: filename}, data));
```

File exists, variables:
* **file**: binary (link?) to the file
* **filename**: style.css
* **data**: content of my package.json
* **headerText**: my template

Any ideas of how to fix this?

**Comment by r007** [comment]
Oh, sorry I found the error. Banner should be written in square brackets, not in {}.
