### ISSUE TITLE
Latest gulp-header release failed to build

### ISSUE THREAD

**Issue by blasky** [tracker1/gulp-header#58]
Latest commit/release today just broke us again...had to pin to your last 1.8.9 release to stay afloat...

/node_modules/gulp-angular-templatecache/node_modules/gulp-header/index.js:30
e = data === false ? headerText : lodashTemplate(headerText)(Object.assign({ f
                                                                    ^
TypeError: undefined is not a function
    at DestroyableTransform.TransformStream [as _transform] (/node_modules/gulp-angular-templatecache/node_modules/gulp-header/index.js:30:84)
    at DestroyableTransform.Transform._read (/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at write (/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)

**Comment by tracker1** [comment]
Okay, are you relying on the file.data (data out of the gulp-data) being available at the root?   Or expressly passing in `false` for the formatting of the header.

I'm not sure when it was added, but there was always the "file" object available directly, and this seems to be the origin of the problem.

I'm removing the function altogether, and this will break people, then only fixing in the 2.x moving forward.

**Comment by blasky** [comment]
Thanks for the quick response. But we're not doing anything. Just including the gulp-angular-templatecache in our package-json which references gulp-header, and which broke today after your commit/release.

**Comment by tracker1** [comment]
Is it working now?  Sorry, but it's hard to tell what the actual problem is... if this change broke it, it should have already been broken.

**Comment by tracker1** [comment]
Are you on a really old version of node?

**Comment by blasky** [comment]
We are currently restricted to an older node (...for unrelated reasons). We will pin our versions of gulp-header and gulp-footer for the time being if need be. Thanks.

**Comment by tracker1** [comment]
Sure thing... you could also patch `Object.assign` which has been in node for a long while now.
